# Generated by Django 2.0 on 2017-12-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=10)),
                ('e_mail', models.EmailField(blank=True, max_length=70)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
