# Generated by Django 2.0 on 2017-12-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20171230_1628'),
        ('users', '0003_auto_20171230_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='project.Projects', verbose_name='Выберите проект'),
        ),
    ]
