# Generated by Django 2.0 on 2017-12-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171230_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
    ]
