# Generated by Django 2.0 on 2017-12-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_projects_students'),
        ('users', '0005_remove_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='project.Projects', verbose_name='Выберите проект'),
        ),
    ]
