# Generated by Django 2.0 on 2017-12-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_projects_students'),
        ('users', '0008_auto_20171231_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
