# Generated by Django 2.0 on 2017-12-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20171231_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='e_mail',
        ),
    ]
