# Generated by Django 2.0.1 on 2018-01-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории для проектов',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.CharField(max_length=64, verbose_name='Описание')),
                ('deadline', models.CharField(max_length=20, verbose_name='Срок сдачи')),
                ('kurator', models.CharField(max_length=64, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('student', models.CharField(max_length=64, verbose_name='Студент')),
                ('importance_type',
                 models.PositiveIntegerField(choices=[(0, 'Высокая'), (1, 'Средняя'), (2, 'Низкая')], default=2,
                                             verbose_name='Важность')),
                ('status_type', models.PositiveIntegerField(choices=[(0, 'Выполнено'), (1, 'Не выполнено')], default=1,
                                                            verbose_name='Статус')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectCategories',
                                   verbose_name='Категория')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Projects',
                                              verbose_name='Выберите проект')),
            ],
            options={
                'verbose_name_plural': 'Задачи для проектов',
            },
        ),
    ]
