# Generated by Django 2.0 on 2017-12-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='importance_type',
            field=models.CharField(choices=[('В', 'Высокая'), ('С', 'Средняя'), ('Н', 'Низкая')], default=0, max_length=1),
        ),
    ]
