# Generated by Django 2.0 on 2017-12-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_todolist_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.CharField(choices=[('Д', 'Дизайн'), ('Р', 'Разработка')], default=0, max_length=1),
        ),
    ]
