# Generated by Django 2.0 on 2017-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status_type',
            field=models.CharField(choices=[('В', 'Выполнено'), ('НВ', 'Не выполнено')], default=0, max_length=1),
        ),
    ]
