# Generated by Django 2.0 on 2017-12-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20171219_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(choices=[(0, 'Д'), (1, 'Дизайн'), (2, 'Р'), (3, 'Разработка')], default='Д', max_length=1, verbose_name='Категория'),
        ),
    ]
