# Generated by Django 2.0 on 2017-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20171219_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Дизайн'), (1, 'Разработка')], default=0, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='importance_type',
            field=models.PositiveIntegerField(choices=[(0, 'Высокая'), (1, 'Средняя'), (2, 'Низкая')], default=2, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status_type',
            field=models.PositiveIntegerField(choices=[(0, 'Выполнено'), (1, 'Не выполнено')], default=1, verbose_name='Статус'),
        ),
    ]
