# Generated by Django 2.0 on 2017-12-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_project'),
        ('project', '0015_auto_20171230_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='students',
            field=models.ManyToManyField(to='users.User', verbose_name='Выберите проект'),
        ),
    ]
