# Generated by Django 2.0 on 2017-12-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_projects_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='project',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
