# Generated by Django 2.0 on 2017-12-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20171230_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='students',
        ),
    ]
